title: Mariam Badr
logo: /images/profile-pic.png
#show_downloads: true
theme: jekyll-theme-minimal            
navbar-links:
  About Me: "aboutme"
  Resources:
    - linkedin_username: mariam-badr2
    - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: "https://deanattali.com"
