title: Mariam Badr
logo: /images/profile-pic.png
#show_downloads: true
theme: jekyll-theme-minimal            
social-network-links:
  email: "Mariam.badr@outlook.com"
  github: "Mariam1000"
  linkedin: "mariam-badr2"


