title: Mariam Badr
logo: /images/profile-pic.png
#show_downloads: true
theme: jekyll-theme-minimal
<div class="badge-base LI-profile-badge" data-locale="en_US" data-size="medium" data-theme="light" data-type="VERTICAL" data-vanity="mariam-badr2" data-version="v1"><a class="badge-base__link LI-simple-link" href="https://eg.linkedin.com/in/mariam-badr2?trk=profile-badge">Mariam Badr</a></div>
              
